// import { useCallback, useEffect } from "react";
// import { usePermission } from "../hooks/permissionStore";
// const {getPermission,permissionData} = usePermission();

//  const fetchDataTable = useCallback(async () => {
//     try {
//       await getPermission();
//     } catch (error) {
//       return;
//     }
//   }, [getPermission]);

//   useEffect(() => {
//     fetchDataTable();
//   }, [fetchDataTable]);

//ลองส่ง API enum เพื่อมาแสดงที่หน้าบ้าน
export const PermissionEnum = Object.freeze({
  EMPLOYEE_VIEW: "EMPLOYEE_VIEW",
  EMPLOYEE_CREATE: "EMPLOYEE_CREATE",
  EMPLOYEE_UPDATE: "EMPLOYEE_UPDATE",

  SETTING: "SETTING",
  SETTING_EMPLOYEE: "SETTING_EMPLOYEE",
  SETTING_USER: "SETTING_USER",
  SETTING_NAME_TITLE: "SETTING_NAME_TITLE",
  SETTING_EDUCATION: "SETTING_EDUCATION",
  SETTING_JOB: "SETTING_JOB",
  SETTING_JOB_CATEGORY: "SETTING_JOB_CATEGORY",
  SETTING_LEVEL: "SETTING_LEVEL",
  SETTING_POSITION: "SETTING_POSITION",
  SETTING_CONTRACTOR: "SETTING_CONTRACTOR",
  SETTING_EMPLOYEE_TYPE: "SETTING_EMPLOYEE_TYPE",
  SETTING_DEDUCTION_TYPE: "SETTING_DEDUCTION_TYPE",
  SETTING_ROLE: "SETTING_ROLE",
  SETTING_PERMISSION: "SETTING_PERMISSION",
  SETTING_HOLIDAY: "SETTING_HOLIDAY",
  SETTING_OT_CATEGORY: "SETTING_OT_CATEGORY",
  SETTING_ANNOUNCEMENT: "SETTING_ANNOUNCEMENT",
  SETTING_FLOW: "SETTING_FLOW",
  SETTING_USERJOB: "SETTING_USERJOB",

  OT_CREATE: "OT_CREATE",
  OT_DELETE: "OT_DELETE",

  OT_PENDING: "OT_PENDING", //cแสดงรายการที่รอโอที
  OT_APPROVAL: "OT_APPROVAL",
  OT_REJECT: "OT_REJECT",
  OT_ONLY_APPROVER: "OT_ONLY_APPROVER",
  OT_UPDATE: "OT_UPDATE",

  USER_RESET_PASSWORD: "USER_RESET_PASSWORD", //admin can reset only

  USER_CREATE: "USER_CREATE",
  USER_DELETE: "USER_DELETE",
  USER_UPDATE: "USER_UPDATE",

  ROLE_PERM_VIEW: "ROLE_PERM_VIEW",
  ROLE_PERM_UPDATE: "ROLE_PERM_UPDATE",
  ROLE_PERM_CREATE: "ROLE_PERM_CREATE",

  ROLE_CREATE: "ROLE_CREATE",
  ROLE_DELETE: "ROLE_DELETE",
  ROLE_UPDATE: "ROLE_UPDATE",

  EMPLOYEETYPE_VIEW: "EMPLOYEETYPE_VIEW",
  EMPLOYEETYPE_CREATE: "EMPLOYEETYPE_CREATE",
  EMPLOYEETYPE_DELETE: "EMPLOYEETYPE_DELETE",
  EMPLOYEETYPE_UPDATE: "EMPLOYEETYPE_UPDATE",

  ANNOUNCEMENT_VIEW: "ANNOUNCEMENT_VIEW",
  ANNOUNCEMENT_UPDATE: "ANNOUNCEMENT_UPDATE",
  ANNOUNCEMENT_CREATE: "ANNOUNCEMENT_CREATE",

  DEDUCTIONTYPE_CREATE: "DEDUCTIONTYPE_CREATE",
  DEDUCTIONTYPE_DELETE: "DEDUCTIONTYPE_DELETE",
  DEDUCTIONTYPE_UPDATE: "DEDUCTIONTYPE_UPDATE",
  DEDUCTIONTYPE_VIEW: "	DEDUCTIONTYPE_VIEW",

  EDUCATION_CREATE: "EDUCATION_CREATE",
  EDUCATION_DELETE: "EDUCATION_DELETE",
  EDUCATION_UPDATE: "EDUCATION_UPDATE",
  EDUCATION_VIEW: "EDUCATION_VIEW",

  FLOW_CREATE: "FLOW_CREATE",
  FLOW_UPDATE: "FLOW_UPDATE",
  FLOW_VIEW: "FLOW_VIEW",

  PERM_CREATE: "PERM_CREATE",
  PERM_DELETE: "PERM_DELETE",
  PERM_UPDATE: "PERM_UPDATE",
  PERM_VIEW: "PERM_VIEW",

  JOB_CATEGORY_CREATE :"JOB_CATEGORY_CREATE",
  JOB_CATEGORY_UPDATE :"JOB_CATEGORY_UPDATE",
  JOB_CATEGORY_VIEW :"JOB_CATEGORY_VIEW",

  JOB_CREATE :"JOB_CREATE",
  JOB_DELETE :"JOB_DELETE",
  JOB_UPDATE :"JOB_UPDATE",
  JOB_VIEW :"JOB_VIEW",

  USERJOB_UPDATE :"USERJOB_UPDATE",
  USERJOB_VIEW :"USERJOB_VIEW"
});

export const RoleEnum = Object.freeze({
  SUPER: "SUPER",
  HR: "HR",
  EMPLOYEE: "Employee",
});
