export const PermissionEnum = Object.freeze({
  EMPLOYEE_VIEW: "EMPLOYEE_VIEW",
  EMPLOYEE_CREATE: "EMPLOYEE_CREATE",
  EMPLOYEE_UPDATE: "EMPLOYEE_UPDATE",

  SETTING: "SETTING",
  SETTING_EMPLOYEE: "SETTING_EMPLOYEE",
  SETTING_USER: "SETTING_USER",
  SETTING_NAME_TITLE: "SETTING_NAME_TITLE",
  SETTING_EDUCATION: "SETTING_EDUCATION",
  SETTING_JOB: "SETTING_JOB",
  SETTING_JOB_CATEGORY: "SETTING_JOB_CATEGORY",
  SETTING_LEVEL: "SETTING_LEVEL",
  SETTING_POSITION: "SETTING_POSITION",
  SETTING_CONTRACTOR: "SETTING_CONTRACTOR",
  SETTING_EMPLOYEE_TYPE: "SETTING_EMPLOYEE_TYPE",
  SETTING_DEDUCTION_TYPE : "SETTING_DEDUCTION_TYPE",
  SETTING_ROLE : "SETTING_ROLE",
  SETTING_PERMISSION : "SETTING_PERMISSION",
  SETTING_HOLIDAY :"SETTING_HOLIDAY",
  SETTING_OT_CATEGORY :"SETTING_OT_CATEGORY",
  SETTING_ANNOUNCEMENT :"SETTING_ANNOUNCEMENT",
  SETTING_FLOW : "SETTING_FLOW",
  SETTING_USERJOB :"SETTING_USERJOB",

  OT_CREATE: "OT_CREATE",
  OT_DELETE: "OT_DELETE",

  OT_PENDING: "OT_PENDING", //cแสดงรายการที่รอโอที
  OT_APPROVAL :"OT_APPROVAL",
  OT_REJECT :"OT_REJECT",
  OT_ONLY_APPROVER :"OT_ONLY_APPROVER",
  OT_UPDATE :"OT_UPDATE",

  USER_RESET_PASSWORD : "USER_RESET_PASSWORD", //admin can reset only

  USER_CREATE : "USER_CREATE",
  USER_DELETE : "USER_DELETE",
  USER_UPDATE : "USER_UPDATE",

  ROLE_PERM_VIEW :  "ROLE_PERM_VIEW",
  ROLE_PERM_UPDATE :"ROLE_PERM_UPDATE",
  ROLE_PERM_CREATE : "ROLE_PERM_CREATE"

});

export const RoleEnum = Object.freeze({
  SUPER: "SUPER",
  HR: "HR",
  EMPLOYEE: "Employee",
});
