export const SpanTypeEnum = Object.freeze({
  ROW: "rowSpan",
  COL: "colSpan",
});

export const OTtimeOptions = {
  otStart: [
    { time: "04:00", timeType: 0 },
    { time: "04:30", timeType: 0 },
    { time: "05:00", timeType: 0 },
    { time: "05:30", timeType: 0 },
    { time: "06:00", timeType: 0 },
    { time: "06:30", timeType: 0 },
    { time: "07.00", timeType: 0 },
    { time: "07:30", timeType: 0 },
    { time: "08:00", timeType: 0 },
    { time: "08:30", timeType: 0 },
    { time: "09:00", timeType: 0 },
    { time: "09:30", timeType: 0 },
    { time: "10:00", timeType: 0 },
    { time: "10:30", timeType: 0 },
    { time: "11:00", timeType: 0 },
    { time: "11:30", timeType: 0 },
    { time: "12:00", timeType: 0 },
    { time: "12:30", timeType: 0 },
    { time: "13:00", timeType: 0 },
    { time: "13:30", timeType: 0 },
    { time: "17:00", timeType: 0 },
    { time: "18:00", timeType: 0 },
  ],
  otEnd: [
    { time: "08:00", timeType: 0 },
    { time: "08:30", timeType: 0 },
    { time: "12:00", timeType: 0 },
    { time: "12:30", timeType: 0 },
    { time: "13:00", timeType: 0 },
    { time: "13:30", timeType: 0 },
    { time: "17:00", timeType: 0 },
    { time: "17:30", timeType: 0 },
    { time: "18:00", timeType: 0 },
    { time: "18:30", timeType: 0 },
    { time: "19:00", timeType: 0 },
    { time: "19:30", timeType: 0 },
    { time: "20:00", timeType: 0 },
    { time: "20:30", timeType: 0 },
    { time: "21:00", timeType: 0 },
    { time: "21:30", timeType: 0 },
    { time: "22:00", timeType: 0 },
    { time: "22:30", timeType: 0 },
    { time: "23:00", timeType: 0 },
    { time: "00:00", timeType: 1 },
    { time: "00:30", timeType: 1 },
    { time: "01:00", timeType: 1 },
    { time: "01:30", timeType: 1 },
    { time: "02:00", timeType: 1 },
    { time: "02:30", timeType: 1 },
    { time: "03:00", timeType: 1 },
    { time: "03:30", timeType: 1 },
    { time: "04:00", timeType: 1 },
    { time: "04:30", timeType: 1 },
  ],
};

export const ReportTableMockData = {
  headers: [
    {
      spanType: SpanTypeEnum.ROW,
      spanValue: 2,
      style: [],
      headerName: "no.",
    },
    {
      spanType: SpanTypeEnum.ROW,
      spanValue: 2,
      style: [{ minWidth: "180px" }],
      headerName: "ชื่อ",
    },
    {
      spanType: SpanTypeEnum.ROW,
      spanValue: 2,
      style: [{ minWidth: "100px" }],
      headerName: "ตำแหน่ง",
    },
    {
      spanType: SpanTypeEnum.ROW,
      spanValue: 2,
      style: [{ minWidth: "100px" }],
      headerName: "เวลาทำงาน",
    },
    {
      spanType: SpanTypeEnum.ROW,
      spanValue: 2,
      style: [{ minWidth: "100px" }],
      headerName: "ค่าใช้จ่าย",
    },
    {
      spanType: SpanTypeEnum.ROW,
      spanValue: 2,
      style: [{ minWidth: "100px" }],
      headerName: "รวม (ชม.)",
    },
    {
      spanType: SpanTypeEnum.ROW,
      spanValue: 2,
      style: [{ minWidth: "100px" }],
      headerName: "อัตราค่าจ้าง",
    },
    {
      spanType: SpanTypeEnum.ROW,
      spanValue: 2,
      style: [{ minWidth: "100px" }],
      headerName: "ค่าจ้าง (บาท)",
    },
    {
      spanType: SpanTypeEnum.ROW,
      spanValue: 2,
      style: [{ minWidth: "100px" }],
      headerName: "ประกันสังคม 5%",
    },
    {
      spanType: SpanTypeEnum.ROW,
      spanValue: 2,
      style: [{ minWidth: "100px" }],
      headerName: "ค่าจ้าง (บาท)",
    },
    {
      spanType: SpanTypeEnum.COL,
      spanValue: 3,
      style: [{ minWidth: "100px" }],
      headerName: "ค่าดำเนินการ",
    },
    {
      spanType: SpanTypeEnum.ROW,
      spanValue: 2,
      style: [{ minWidth: "100px" }],
      headerName: "ค่าสุทธิ (บาท)",
    },
  ],
  subHeaders: ["กองทุนทดแทน 0.5%", "กองทุนทดแทน 0.5%", "ดำเนินการ 12%"],
  rows: [
    {
      row: 1,
      col: [
        "1",
        "นาง xxxx xxxx",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
      ],
      style: { bg: "bg-danger" },
    },
    {
      row: 2,
      col: [
        "-",
        "-",
        "-",
        "วันทำงาน (วัน)",
        "-",
        "10.00",
        "372.00",
        "3,720.00",
        "(186.00)",
        "3,534.00",
        "372.00",
        "18.60",
        "446.40",
        "4,371.00",
      ],
      style: { bg: "bg-white" },
    },
    {
      row: 3,
      col: [
        "-",
        "-",
        "-",
        "ล่วงเวลา - วันทำงาน (วัน)",
        "-",
        "10.00",
        "372.00",
        "3,720.00",
        "(186.00)",
        "3,534.00",
        "372.00",
        "18.60",
        "446.40",
        "4,371.00",
      ],
      style: { bg: "bg-white" },
    },
    {
      row: 4,
      col: [
        "-",
        "-",
        "-",
        "-",
        "ค่าเช่าห้อง",
        "10.00",
        "372.00",
        "3,720.00",
        "(186.00)",
        "3,534.00",
        "372.00",
        "18.60",
        "446.40",
        "4,371.00",
      ],
      style: { bg: "bg-white" },
    },
  ],
  footers: [
    { colSpan: 13, footerName: "ค่าแรง" },
    { colSpan: 1, footerName: "3,720.00" },
    { colSpan: 13, footerName: "โอที" },
    { colSpan: 1, footerName: "3,720.00" },
    { colSpan: 13, footerName: "รวมทั้งหมด" },
    { colSpan: 1, footerName: "3,720.00" },
  ],
};

export const invoiceData = {
  id: "5df3180a09ea1",
  invoice_no: "873512-28",
  fullname:"อาคารโรงงาน 5 บริษัท ไอ.พี.วัน. จำกัด (IPONE66)",
  email: "ipone66@gmail.com",
  phone: "+91 777-9999",
  address: "lorem ipsum",
  trans_date: "17-08-2022",
  companyID: "10001",
  companyName: "abc company",
  items: [
    {
      sno: 1,
      desc: "FinePix Pro2 3D Camera",
      qty: 2,
      rate: 1600.0,
    },
    {
      sno: 2,
      desc: "Luxury Ultra thin Wrist Watch",
      qty: 1,
      rate: 300.99,
    },
  ],
};
