 export const mockemployeetableData = [
    {
      empId: "00",
      empName: "Sakata Gintoki",
      phone: "0900000000",
      level: 1,
      position: "เจ้าหน้าที่พัฒนาซอฟแวร์",
      workType: "outsourse",
      status: 1,
    },
    {
      empId: "01",
      empName: "Sakata Gintoki",
      phone: "0900000000",
      level: 2,
      position: "เจ้าหน้าที่พัฒนาซอฟแวร์",
      workType: "outsourse",
      status: 2,
    },
    {
      empId: "02",
      empName: "Sakata Gintoki",
      phone: "0900000000",
      level: 3,
      position: "เจ้าหน้าที่พัฒนาซอฟแวร์",
      workType: "outsourse",
      status: 2,
    },
     {
      empId: "00",
      empName: "Sakata Gintoki",
      phone: "0900000000",
      level: 4,
      position: "เจ้าหน้าที่พัฒนาซอฟแวร์",
      workType: "outsourse",
      status: 1,
    },
    {
      empId: "01",
      empName: "Sakata Gintoki",
      phone: "0900000000",
      level: 5,
      position: "เจ้าหน้าที่พัฒนาซอฟแวร์",
      workType: "outsourse",
      status: 1,
    },
    {
      empId: "02",
      empName: "Sakata Gintoki",
      phone: "0900000000",
      level: 6,
      position: "เจ้าหน้าที่พัฒนาซอฟแวร์",
      workType: "outsourse",
      status: 1,
    },
     {
      empId: "00",
      empName: "Sakata Gintoki",
      phone: "0900000000",
      level: 7,
      position: "เจ้าหน้าที่พัฒนาซอฟแวร์",
      workType: "outsourse",
      status:0,
    },
    {
      empId: "01",
      empName: "Sakata Gintoki",
      phone: "0900000000",
      level: 8,
      position: "เจ้าหน้าที่พัฒนาซอฟแวร์",
      workType: "outsourse",
      status: 0,
    },
    {
      empId: "02",
      empName: "Sakata Gintoki",
      phone: "0900000000",
      level: 9,
      position: "เจ้าหน้าที่พัฒนาซอฟแวร์",
      workType: "outsourse",
      status: 1,
    },
     {
      empId: "00",
      empName: "Sakata Gintoki",
      phone: "0900000000",
      level: 1,
      position: "เจ้าหน้าที่พัฒนาซอฟแวร์",
      workType: "outsourse",
      status: 1,
    },
    {
      empId: "01",
      empName: "Sakata Gintoki",
      phone: "0900000000",
      level: 2,
      position: "เจ้าหน้าที่พัฒนาซอฟแวร์",
      workType: "outsourse",
      status: 1,
    },
    {
      empId: "02",
      empName: "Sakata Gintoki",
      phone: "0900000000",
      level: 3,
      position: "เจ้าหน้าที่พัฒนาซอฟแวร์",
      workType: "outsourse",
      status: 0,
    },
     {
      empId: "00",
      empName: "Sakata Gintoki",
      phone: "0900000000",
      level: 4,
      position: "เจ้าหน้าที่พัฒนาซอฟแวร์",
      workType: "outsourse",
      status: 0,

    },
    {
      empId: "01",
      empName: "Sakata Gintoki",
      phone: "0900000000",
      level: 5,
      position: "เจ้าหน้าที่พัฒนาซอฟแวร์",
      workType: "outsourse",
      status: 0,
    }
  ];

  